apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-data-mcp
  namespace: intent-platform
  labels:
    app: customer-data-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-data-mcp
  template:
    metadata:
      labels:
        app: customer-data-mcp
    spec:
      containers:
      - name: customer-data-mcp
        image: vpnet/customer-data-mcp-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: customer-data-mcp-service
  namespace: intent-platform
spec:
  selector:
    app: customer-data-mcp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
