apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-graph-mcp-v2-canary
  namespace: intent-platform
  labels:
    app: knowledge-graph-mcp
    version: "2.0.0"
    deployment: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledge-graph-mcp
      version: "2.0.0"
  template:
    metadata:
      labels:
        app: knowledge-graph-mcp
        version: "2.0.0"
        deployment: canary
    spec:
      containers:
      - name: knowledge-graph-mcp
        image: vpnet/knowledge-graph-mcp-service:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NEO4J_URI
          value: "bolt://neo4j-service:7687"
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: NEO4J_USER
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: NEO4J_PASSWORD
        - name: MCP_API_KEY_BUSINESS_INTENT
          valueFrom:
            secretKeyRef:
              name: mcp-api-keys
              key: MCP_API_KEY_BUSINESS_INTENT
        - name: MCP_API_KEY_ADMIN
          valueFrom:
            secretKeyRef:
              name: mcp-api-keys
              key: MCP_API_KEY_ADMIN
        - name: MCP_API_KEY_MONITORING
          valueFrom:
            secretKeyRef:
              name: mcp-api-keys
              key: MCP_API_KEY_MONITORING
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
