apiVersion: v1
kind: Secret
metadata:
  name: mcp-api-keys
  namespace: intent-platform
type: Opaque
stringData:
  # API key for business-intent-agent to call MCP services
  # In production, generate with: openssl rand -base64 32
  MCP_API_KEY_BUSINESS_INTENT: "change-me-business-intent-key-$(openssl rand -base64 24)"

  # API key for admin/monitoring tools
  MCP_API_KEY_ADMIN: "change-me-admin-key-$(openssl rand -base64 24)"

  # API key for monitoring services
  MCP_API_KEY_MONITORING: "change-me-monitoring-key-$(openssl rand -base64 24)"
---
# ConfigMap with instructions for key rotation
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-security-config
  namespace: intent-platform
data:
  README.md: |
    # MCP API Key Management

    ## Generating New Keys

    Generate secure API keys:
    ```bash
    openssl rand -base64 32
    ```

    ## Rotating Keys

    1. Generate new key
    2. Update secret:
       ```bash
       kubectl create secret generic mcp-api-keys \
         --from-literal=MCP_API_KEY_BUSINESS_INTENT=<new-key> \
         --namespace=intent-platform \
         --dry-run=client -o yaml | kubectl apply -f -
       ```
    3. Restart pods to pick up new keys:
       ```bash
       kubectl rollout restart deployment -n intent-platform
       ```

    ## Key Rotation Schedule
    - Rotate keys every 90 days
    - Immediate rotation if compromise suspected
    - Document rotation in audit log

    ## Security Notes
    - Never commit real keys to version control
    - Use different keys per environment (dev/staging/prod)
    - Monitor failed authentication attempts
    - Implement key expiration in production
