apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-intent-agent
  namespace: intent-platform
  labels:
    app: business-intent-agent
    version: v1.1.0-tmf921
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-intent-agent
  template:
    metadata:
      labels:
        app: business-intent-agent
        version: v1.1.0-tmf921
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: business-intent-agent
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsNonRoot: true
      volumes:
      - name: anthropic-api-key
        secret:
          secretName: anthropic-api-key
          items:
          - key: key
            path: anthropic_api_key
      containers:
      - name: business-intent-agent
        image: vpnet/business-intent-agent:1.1.0-tmf921
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: shared-config
        env:
        - name: NODE_ENV
          value: "development"
        - name: ANTHROPIC_API_KEY_FILE
          value: "/run/secrets/anthropic_api_key"
        - name: MCP_API_KEY_BUSINESS_INTENT
          valueFrom:
            secretKeyRef:
              name: mcp-api-keys
              key: MCP_API_KEY_BUSINESS_INTENT
        - name: MCP_BSS_URL
          value: "http://bss-oss-mcp-service:8080"
        - name: MCP_KNOWLEDGE_GRAPH_URL
          value: "http://knowledge-graph-mcp-service:8080"
        - name: MCP_CUSTOMER_DATA_URL
          value: "http://customer-data-mcp-service:8080"
        volumeMounts:
        - name: anthropic-api-key
          mountPath: "/run/secrets"
          readOnly: true
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
